name: Run specs and generate Code Climate report
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint:
    name: "Linting with Flake8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 ./chartmogul
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       python-versions: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-versions }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel coverage
          pip install -e .[testing]
      - name: Run tests
        run: coverage run -m unittest && coverage xml -i --include='chartmogul/*'